### ISSUE TITLE
cdb release failed

### ISSUE THREAD

**Issue by BuckarooBanzay** [FreeLANMan/RealMoon2021#7]
Currently the cdb release fails with:
```
"Error validating package: Error while reading /mods/vacuum-moon/mod.conf: Line 3: Expected line to contain \'=\'"
```

This here is the cause:
https://github.com/FreeLANMan/RealMoon2021/blob/418d3628992fa2afd93bc16ddeb102ff8c332b06/mods/vacuum-moon/mod.conf#L3-L4

Those 2 lines are settings and don't really belong in a `mod.conf`

**Comment by FreeLANMan** [comment]
Thanks
